03/13/2021 11:30:14 PM [ERROR] [fullNewsSearch.py:54] >> ERROR : name 'asfdasdf' is not defined
03/17/2021 04:27:44 AM [ERROR] [fullNewsSearch.py:53] >> ERROR : local variable 'num' referenced before assignment
03/17/2021 11:55:40 AM [ERROR] [fullNewsSearch.py:53] >> ERROR : HTTPConnectionPool(host='localhost', port=8081): Max retries exceeded with url: /stock/VI_NewsReg (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022AF9623430>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다'))
03/18/2021 02:59:09 AM [ERROR] [fullNewsSearch.py:53] >> ERROR : HTTPConnectionPool(host='localhost', port=8081): Max retries exceeded with url: /stock/VI_NewsReg1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F4E9AA4100>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다'))
03/26/2021 12:54:02 AM [ERROR] [fullNewsSearch.py:53] >> ERROR : HTTPConnectionPool(host='localhost', port=8081): Max retries exceeded with url: /stock/VI_NewsReg (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000219CD041100>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다'))
03/31/2021 08:35:29 PM [ERROR] [fullNewsSearch.py:53] >> ERROR : HTTPConnectionPool(host='localhost', port=8081): Max retries exceeded with url: /stock/VI_NewsReg (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016CA4B16C40>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다'))
03/31/2021 08:42:03 PM [ERROR] [fullNewsSearch.py:53] >> ERROR : HTTPConnectionPool(host='localhost', port=8081): Max retries exceeded with url: /stock/VI_NewsReg (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B1181110D0>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다'))
03/31/2021 09:33:43 PM [ERROR] [fullNewsSearch.py:53] >> ERROR : [Errno 22] Invalid argument
04/30/2021 12:01:29 AM [ERROR] [fullNewsSearch.py:53] >> ERROR : [Errno 22] Invalid argument
05/04/2021 04:50:08 PM [ERROR] [fullNewsSearch.py:53] >> ERROR : [Errno 22] Invalid argument
06/17/2021 02:03:45 AM [ERROR] [fullNewsSearch.py:53] >> ERROR : HTTPConnectionPool(host='localhost', port=8081): Max retries exceeded with url: /stock/VI_NewsReg (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023756079640>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다'))
06/17/2021 02:12:23 AM [ERROR] [fullNewsSearch.py:53] >> ERROR : HTTPConnectionPool(host='localhost', port=8081): Max retries exceeded with url: /stock/VI_NewsReg (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FC42BB9F40>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다'))
02/21/2022 06:40:36 PM [ERROR] [fullNewsSearch.py:53] >> ERROR : name 'send_json' is not defined
02/21/2022 09:48:58 PM [ERROR] [fullNewsSearch.py:53] >> ERROR : [Errno 22] Invalid argument
